[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
token_contract = "BydD8yQtb1kWB7WUnzzq9KduCDzSvUUi1nuoz9wHDM1X"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "mocha --require ts-node/register -t 1000000 tests/**/*.ts"
