[workspace]
members = ["programs/*"]
resolver = "2"

[profile.release]
overflow-checks = true
lto = "thin"
codegen-units = 1
panic = "abort"
strip = "symbols"
opt-level = "z"
incremental = false

[profile.release.build-override]
opt-level = 3
codegen-units = 16